//
// Created by Matthew Lourenco on 20/06/2020.
//

#ifndef OTHELLO_AI_H
#define OTHELLO_AI_H

#include "board.h"
#include "boardAnalysis.h"
#include <exception>
#include <vector>

// Thrown when the ai was unable to generate any data
class no_generation: public std::exception {
    int size;

public:
    const char* what() const noexcept override {
        return "No data was generated by ai";
    }
};

struct scores {
    int my, op; // current score of ai(my) and player(op)

    scores(): my(0), op(0) {}
};

std::ostream& operator<<(std::ostream& os, const scores& s) {
    os << "{" << s.my << ", " << s.op << "}";
    return os;
}

struct possibleFuture {
    const Board *const b;
    const bool aiTurn;
    scores *const tileScore;

    possibleFuture(const Board *b_, bool aiTurn_, scores *tileScore_): b(b_), aiTurn(aiTurn_), tileScore(tileScore_) {}
    ~possibleFuture() {delete b;}
};

// AI that is restricted to one second of time to make decisions
class Ai {
    const Board *const b; // pointer to the current game board
    const char aiRole, opRole; // P1 or P2
    std::vector<scores> data; // calculated best scores for each player per space

public:
    /* Constructor */
    Ai(Board *b_, char role_);

    /* Destructor */
    ~Ai();

    /* Methods */
    // Finds the best possible move in one second of time
    std::pair<int, int> findBestMove();
};


#endif //OTHELLO_AI_H
